### ISSUE TITLE
添加计分板倒计时、正计时功能

### ISSUE THREAD

**Issue by EarthDLL** [USFrameTeam/Unknown-Server-Framework#3]
QQ提案
设置特定的计分板，可以自动执行倒计时、正计时功能
![Screenshot_20240309_192248](https://github.com/EarthDLL/Unknown-Server-Framework/assets/100025289/561002ba-095d-4f5f-8337-4506de9b3d83)

**Comment by MinecraftFish** [comment]
这不是有了吗
